# Generated by Django 5.2 on 2025-04-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_time', '0002_actor_actor_name_en_actor_actor_name_ru_actor_bio_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
