# Generated by Django 5.2 on 2025-04-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_time', '0004_remove_movie_director_director_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='movie_time.director'),
        ),
    ]
